### ISSUE TITLE
Peer Review: jtkovacs

### ISSUE THREAD

**Issue by asford** [UWSEDS-aut17/OPMxplore#3]
# Group Peer Review

As a "group" peer review, review the team's progress toward developing a functional specification [homework 5](https://github.com/UWSEDS/hw5-aut17) and component design [homework 6](https://github.com/UWSEDS/hw6-aut17).

The team should have a discoverable functional specification with:

- [x] A target user/consumer profile.
- [x] A problem statement.
- [x] A list of 2-3 cases.

The should also provide a general including:

- [x] A list of 3-4 components.
- [x] Component names.
- [x] A component purpose
- [x] Component inputs and outputs.
- [x] Pseudocode for design.

**Comment by jtkovacs** [comment]
**Explanation for the marks above:**

- **User profile** was clear and specific
- Your project seems seems extremely ambitious and perhaps that's why the **problem statement** is so broad and the **use cases** are so abstract. For my team's project, our use cases consist of six major operations/interactions the user will perform with the system, for example "summarize Facebook data" or "Identify peak hours for social media activity". I think making these design deliverables more narrow and specific is required to satisfy the assignment and might also help you manage the scope of your project for the remainder of the quarter---it seems like you all have a TON of work you hope to do! 
- I gleaned most of the required information about **components** from your README, but didn't see the requisite level of detail on the components yet (I understand you're probably still iterating at too high a level to write psuedocode---my team is in the same place, basically, and our project is much more tightly scoped. BUT you probably could elaborate component input/outputs at the level of file types or data types).

**Extra thoughts if interested:**

- My understanding of the assignment was to put the functional specs and component specs in the `docs` directory.
- Your README seems like a team coordination/planning document  rather than a welcome page explaining the project to someone who doesn't know about it.

**Comment by fpDNA** [comment]
Thanks Jacob! Our project changed many times and I think we have addressed these issues now.

**Comment by fpDNA** [comment]
Thanks Jacob! Your comment was very very helpful. We have addressed those issues now.
